---
galaxy_info:
  author: Klaas Demter
  description: Role to configure Microsoft package repo.
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - linux
    - system
    - ansible

dependencies: []
collections: []
...
