---
namespace: cloud
name: azure_ops
version: 3.0.0
authors:
  - Ansible (https://github.com/ansible)
description: A collection of content (roles, playbooks, etc) for Ansible Automation Platform on Azure.
documentation: ''
homepage: https://github.com/redhat-cop/cloud.azure_ops
issues: https://github.com/redhat-cop/cloud.azure_ops/issues
license_file: LICENSE
readme: README.md
repository: https://github.com/redhat-cop/cloud.azure_ops
tags:
  - cloud
  - azure
  - infrastructure
dependencies:
  azure.azcollection: ">=3.3.0"
build_ignore:
  - '.tox'
  - '.git'
  - '.github'
  - '.gitignore'
