---
- name: Fail on invalid delete option
  fail:
    msg: "Invalid value for remove_on_absent. Valid values include 'all', 'all_autocreated', 'network_interfaces', 'virtual_storage', or 'public_ips'"
  when: remove_on_absent not in ['all', 'all_autocreated', 'network_interfaces', 'virtual_storage', 'public_ips']

- name: Fail when resource group doesn't exist
  fail:
    msg: "Resource group {{ azure_resource_group }} does not exist"
  when: rg_info.resourcegroups | length == 0

- name: Delete Virtual Machine and specified associated resources
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name }}"
    remove_on_absent: "{{ remove_on_absent | default(omit) }}"
    state: absent