---
- name: Delete storage account
  azure.azcollection.azure_rm_storageaccount:
    resource_group: "{{ azure_manage_storage_account_resource_group }}"
    name: "{{ azure_manage_storage_account_name }}"
    state: absent
