---
- name: Replace invalid chars in name
  ansible.builtin.set_fact:
    vm_name: "{{ azure_virtual_machine_with_public_ip_vm.name | regex_replace('[^a-zA-Z0-9]', '-') }}"

- name: Get resource group info
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
  register: azure_virtual_machine_with_public_ip_rg_info

- name: Fail when resource group doesn't exist
  ansible.builtin.fail:
    msg: Resource group {{ azure_virtual_machine_with_public_ip_resource_group }} does not exist
  when: 
  - azure_virtual_machine_with_public_ip_rg_info.resourcegroups | length == 0
  - azure_virtual_machine_with_public_ip_operation != 'create'

- name: Power Off VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ vm_name }}"
    started: false
  when: azure_virtual_machine_with_public_ip_operation == 'power_off'

- name: Deallocate VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ vm_name }}"
    allocated: false
  when: azure_virtual_machine_with_public_ip_operation == 'deallocate'

- name: Power On VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ vm_name }}"
    started: true
  when: azure_virtual_machine_with_public_ip_operation == 'power_on'

- name: Restart VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ vm_name }}"
    restarted: true
  when: azure_virtual_machine_with_public_ip_operation == 'restart'

- name: Create or delete VM
  ansible.builtin.include_tasks: "{{ azure_virtual_machine_with_public_ip_operation }}.yml"
  when: azure_virtual_machine_with_public_ip_operation in ['create', 'delete']
