---
- name: Set azcmagent proxy setting
  become: true
  ansible.builtin.command:
    argv:
      - azcmagent
      - config
      - set
      - proxy.url
      - "{{ azure_configure_archost_proxy_url }}"
  register: azure_configure_archost_proxy_set
  changed_when: azure_configure_archost_proxy_set.rc == 0
