---
- name: Use azure arc agent to connect to azure
  # This command produces output that includes an access token
  no_log: true
  ansible.windows.win_command:
    argv:
      - "{{ ansible_env['ProgramFiles'] }}/AzureConnectedMachineAgent/azcmagent.exe"
      - connect
      - --resource-group
      - "{{ azure_configure_archost_resource_group }}"
      - --tenant-id
      - "{{ azure_configure_archost_tenant_id }}"
      - --location
      - "{{ azure_configure_archost_location }}"
      - --subscription-id
      - "{{ azure_configure_archost_subscription_id }}"
      - --cloud
      - "{{ azure_configure_archost_cloud }}"
      - --tags
      - "{{ azure_configure_archost_processed_tags }}"
      - --access-token
      - "{{ azure_configure_archost_access_token.access_token }}"
      - --json
  # If this command is run, it will always change the connection status from unconnected to connected
  changed_when: true
  register: azure_configure_archost_azcmagent_connect_json
