---
- name: Check if Connected Machine Agent is Downloaded
  ansible.windows.win_stat:
    path: C:\AzureConnectedMachineAgent.msi
    get_checksum: False
  register: azure_configure_archost_azcmagent_win_downloaded

- name: Download the Connected Machine Agent on Windows servers
  ansible.windows.win_get_url:
    url: https://aka.ms/AzureConnectedMachineAgent
    dest: C:\AzureConnectedMachineAgent.msi
  register: _azure_configure_archost_response
  delay: 5
  retries: 50
  ignore_errors: false
  until:
    - _azure_configure_archost_response.status_code is defined
    - _azure_configure_archost_response.status_code == 200
  when: not azure_configure_archost_azcmagent_win_downloaded.stat.exists

- name: Install the Connected Machine Agent on Windows servers
  ansible.windows.win_package:
    path: C:\AzureConnectedMachineAgent.msi
  when: not azure_configure_archost_azcmagent_win_downloaded.stat.exists
