---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  when: not ansible_facts.packages is defined

- name: Install packages-microsoft-prod if not installed already
  when: not ansible_facts['packages']['packages-microsoft-prod'] is defined
  block:
    - name: Install packages.microsoft.com repository file (proxy)
      when: proxy is defined
      become: true
      ansible.builtin.package:
        name: "{{ azure_repo_microsoft_prod_package_url }}"
        state: present
        disable_gpg_check: true
      environment:
        https_proxy: "http://{{ proxy['hostname'] }}:{{ proxy['port'] }}"

    - name: Install packages.microsoft.com repository file (no proxy)
      when: not proxy is defined
      become: true
      ansible.builtin.package:
        name: "{{ azure_repo_microsoft_prod_package_url }}"
        state: present
        disable_gpg_check: true

- name: Add proxy to yum repository for packages-microsoft-prod if needed (ansible_os_family == RedHat)
  when:
    - proxy is defined
    - ansible_os_family == 'RedHat'
  become: true
  community.general.ini_file:
    path: /etc/yum.repos.d/microsoft-prod.repo
    mode: '0600'
    owner: root
    group: root
    no_extra_spaces: true
    section: packages-microsoft-com-prod
    option: proxy
    value: "http://{{ proxy['hostname'] }}:{{ proxy['port'] }}"
